### ISSUE TITLE
Support for CPAN modules

### ISSUE THREAD

**Issue by book** [Grinnz/perldoc-browser#13]
I like the lean interface of the site, and wondered if it would make sense add support for showing the docs of CPAN modules (not part of the core Perl distribution).

**Comment by Grinnz** [comment]
It will show any docs that are installed, but I do not plan to use the perldoc.pl instance for any CPAN docs to avoid confusion/complexity. Another instance could certainly do so.

**Comment by Grinnz** [comment]
I've set up https://cpandoc.grinnz.com/ as an instance that could show arbitrary CPAN module documentation, but to do so each CPAN module needs to be installed. I can keep a cpanfile of such CPAN modules to install, but I'm unsure of how to populate or maintain this list. Any ideas?

**Comment by Grinnz** [comment]
I've decided for now to use Task::Kensho as both the homepage and list of CPAN modules to display (in addition to perlsecret). I'll open a new issue for any suggestions.
