### ISSUE TITLE
slow on /perluniprops

### ISSUE THREAD

**Issue by daxim** [Grinnz/perldoc-browser#16]
Despite its size, <https://perldoc.pl/perluniprops> loads fine with 3rd party domains blocked (bootstrapcdn.com, cloudflare.com, jquery.com).

With them enabled, browser performance takes a nosedive: scrolling becomes choppy, browser UI/chrome interactivity lags seconds behind, renders only up to the big table, complete page only finishes after 10 seconds. I guess it's the fault of syntax highlighting, but I didn't verify. Can this be done async or otherwise improved?

**Comment by Grinnz** [comment]
I can reproduce the choppy scrolling but not the slow loading time. What browser are you using? Can you use your browser debug tools to determine where the delay occurs?

**Comment by bpj** [comment]
Same problem on Firefox 67.0.1
FF almost freezes completely.

**Comment by daxim** [comment]
As suspected, it's the syntax highlighter. Also Fx 67

![](https://user-images.githubusercontent.com/104814/59930954-6decf700-9433-11e9-8075-0332b9738b0f.png)

**Comment by Grinnz** [comment]
I have disabled syntax highlighting on any verbatim block with over 5000 characters, which should prevent this issue. Thanks for the report.
