### ISSUE TITLE
Navigation additions

### ISSUE THREAD

**Issue by Grinnz** [Grinnz/perldoc-browser#19]
While perl(1) is a comprehensive overview of the documentation, it may be overwhelming to use for navigation. Additional navigation links may be useful, as well as possibly additional index pages extracted from perl(1).

**Comment by scottchiefbaker** [comment]
I agree with this... perl(1) isn't the best homepage for navigation. A simplified index would be less daunting to a novice.

**Comment by Grinnz** [comment]
I am trialing a new main index page extracted from perl(1) as well as a new dropdown navigation menu. Currently visible at https://sandbox.perldoc.grinnz.com/

**Comment by scottchiefbaker** [comment]
I like this much better than the previous version. +1 from me.

**Comment by matthewpersico** [comment]
Suggestions:

- Change MANUAL SECTIONS to MANUALS and TUTORIALS. The former phrasing begs the question "Where are the AUTOMATED SECTIONS".
- Move the perl(1) link up from being a footnote into the MANUALS and TUTORIALS section, so that those of us that prefer it can get at it faster.

**Comment by Grinnz** [comment]
Thanks for the suggestions, I've made changes along these lines.

**Comment by matthewpersico** [comment]
Wow. The flow is even better than I imagined!

**Comment by Grinnz** [comment]
This has been deployed. Thanks all for the feedback.
