### ISSUE TITLE
Architecture specific issue finding POD

### ISSUE THREAD

**Issue by kiwiroy** [Grinnz/perldoc-browser#20]
Thanks for this browser. I've been using the public instance and wanted to have a local copy running for offline working too, but I had this issue.

`Pod::Simple::Search->find` suffers an issue perl-pod/pod-simple#108 which leads to `$search->find('perlmodlib', @$inc_dirs)` returning undef, halting effective installation on affected architectures (Darwin for me).

https://github.com/Grinnz/perldoc-browser/blob/b0f60c879e701c3d1987a4e3cbcd3c2ca6c15a70/lib/PerldocBrowser/Plugin/PerldocInstall.pm#L31

After indexing the install, the following results mainly in redirects to metacpan.

https://github.com/Grinnz/perldoc-browser/blob/b0f60c879e701c3d1987a4e3cbcd3c2ca6c15a70/lib/PerldocBrowser/Plugin/PerldocRenderer.pm#L66-L69

There is a workaround in 7fac744

**Comment by Grinnz** [comment]
Please let me know if https://github.com/Grinnz/perldoc-browser/commit/76c8194db6dde2ddf636c32861978ab3ad182cb8 resolves the issue. Thanks for the report.

**Comment by kiwiroy** [comment]
@Grinnz, thanks that's the resolution.
