### ISSUE TITLE
Drop a hint somewhere that QuickSearch via Smart keyword is supported

### ISSUE THREAD

**Issue by Wolf-at-SO** [Grinnz/perldoc-browser#28]
I really don't get why only a minority of programmers use (or even know) it, I don't know how I could live without it. I hope the German screenshot is not too disturbing (some slightly outdated English ones are on [Super User](https://superuser.com/a/116747/391675)), I think most will get the point.
![QuickSearch-Firefox](https://user-images.githubusercontent.com/29630128/79973648-3e19e000-8498-11ea-889a-3e880364d371.png)

BTW: great work :) 

Seems the official perl docs initiative has stopped somehow? I really don't understand why this happened.

**Comment by Grinnz** [comment]
Sorry I don't understand what this refers to, but perhaps it is because the search includes an opensearch configuration: https://perldoc.pl/opensearch.xml

**Comment by Wolf-at-SO** [comment]
Yes, that's what I mean - I searched for it but obviously didn't find the right term, it's a feature in perldoc.pl that https://perldoc.perl.org seems to be missing

In case you didn't know: Firefox (as an example) adds the website-internal search to its search engine collection, the user can access it by using a keyword within the address line, so navigating to the website's home page for doing the actual search can be skipped. After I got to know this way of searching, I switched to searching Amazon (a), YouTube (y) and Wikipedia (w), and even Google (g), because I use an alternative search engine by default. I can't imagine working without this feature anymore and explain it at every opportunity to people (even developers!) who obviously have never heard of it. Sorry should I have bored you with all this, because it's all well known.

**Comment by Grinnz** [comment]
I don't really think it needs to mentioned that basic search features are supported but if so it would be part of a much larger description of features that perldoc.perl.org is missing :smiley: I believe this feature was requested by @haarg, glad it's useful.

**Comment by Wolf-at-SO** [comment]
I see, thanks for having a look on it.
