### ISSUE TITLE
Respond with the same hostname

### ISSUE THREAD

**Issue by briandfoy** [Grinnz/perldoc-browser#29]
perldoc.perl.org now points to perldoc.pl. The response changes the hostname from perldoc.perl.org to perldoc.pl. I'd like to keep the same host from the request.

**Comment by Grinnz** [comment]
That is because perldoc.perl.org is set up as a HTTP redirect, before this site is reached. It is up to @rspier and @abh how that is configured.

**Comment by rspier** [comment]
There are advantages and disadvantages to both options.  We're still evaluating what we want to do here moving forward.

**Comment by jwrightecs** [comment]
Might want to switch it to a 302 until this is resolved, for search engine reasons

**Comment by Grinnz** [comment]
perldoc.perl.org is now a Fastly-backed caching layer so the redirect no longer occurs. You may need to clear your browser's cache if it's cached some of the 301 redirects to perldoc.pl in the past couple days. Thanks @rspier
