### ISSUE TITLE
OpenDNS flags perldoc.pl as 'malware'

### ISSUE THREAD

**Issue by MartinMcGrath** [Grinnz/perldoc-browser#3]
Thanks for the great work on perldoc.pl!

The OpenDNS issue is perhaps due to the IP being on some lists:

https://perlmonks.org/?node_id=1217369

**Comment by Grinnz** [comment]
I'm not sure where that IP came from; the IP that perldoc.pl resolves to is 159.89.255.139, which seems fine.

**Comment by MartinMcGrath** [comment]
Thanks for the quick response. This seems like a PEBCAK issue, I missed the leading 1.  I'll so some more digging later once I've setup OpenDNS here to validate the initial finding.

**Comment by Grinnz** [comment]
Thank you for looking into it, and for spreading the word. :smile:

**Comment by MartinMcGrath** [comment]
Just an FYI, this was tested and showing as blocked to various people on their page:

https://malware.opendns.com/main?url=perldoc.pl

A couple of us requested unblocking, and reported that the OpenDNS page had problems (it now no longer seems to work at all).

After a short while it seems to have had the malware flag removed from their system.
