### ISSUE TITLE
Styling at "tablet" width causes the search input to overlap the viewport

### ISSUE THREAD

**Issue by scottchiefbaker** [Grinnz/perldoc-browser#30]
Viewing the site at tablet width (768px) causes the search form at the top to overlap the viewport and cause the page to be wider that it needs to be. This results in the page being able to be zoomed-out on a tablet to fit the search bar. Chrome and Firefox both exhibit this behavior on my tablet.

This can be easily reproduced in Firefox if you go in to "Responsize Design Mode" and set the mode to iPad.

**Comment by Grinnz** [comment]
Seems there are too many things in the menu bar and some will need to get hidden at the "md" breakpoint.

**Comment by scottchiefbaker** [comment]
Just to test I hid: Dev, Contact, and Github and it looks pretty decent @ 768px. 

![image](https://user-images.githubusercontent.com/3429760/94702784-0179cc80-02f3-11eb-9a38-a59b616bd4fc.png)

**Comment by scottchiefbaker** [comment]
One could make an argument to keep **contact**, and get rid of **perl** as the latter is redundant. 

Right now **Perldoc Browser** and **perl** take you to the same place (different URLs but same content).

**Comment by Grinnz** [comment]
Not quite, the `perl` link goes to the index page of the currently selected version whereas the branded link always goes to the homepage.

**Comment by Grinnz** [comment]
What I may do is move the contact information into the footer of each page (people expect it there) and since that also includes the link to github, both of those can be removed from the menu.

**Comment by scottchiefbaker** [comment]
I like that solution... sounds good to me.

**Comment by Grinnz** [comment]
From my dev console this appears to be solved now by https://github.com/Grinnz/perldoc-browser/commit/551323990a796d1dc92ecd5240e55b2e5906df77 but will need to keep in mind the medium breakpoint in future changes to the menu bar.

**Comment by scottchiefbaker** [comment]
This doesn't appear to be solved for me. I still see the search box overflowing the navbar at the top by about 6em. It's definitely better, but still not "solved".

I've done a hard refresh and it's persisting. Maybe I'm missing something?

**Comment by scottchiefbaker** [comment]
FWIW it's much **more** pronounced on my real tablet than Desktop Firefox in tablet mode... although both exhibit the behaviour.

**Comment by Grinnz** [comment]
I'm now hiding the extra index page links at the md breakpoint.

**Comment by scottchiefbaker** [comment]
Just checked my tablet and Firefox desktop. Both look good now.

Thanks for the quick fix.

**Comment by Grinnz** [comment]
Navigation links are now contained in a dropdown which should keep this issue from resurfacing.
