### ISSUE TITLE
Links to core module letters aren't preserved

### ISSUE THREAD

**Issue by scottchiefbaker** [Grinnz/perldoc-browser#31]
Previous documentation had a page dedicated to each letter of the alphabet for core modules. Search engines still have several of theses in their indexes:

https://perldoc.perl.org/index-modules-T.html
https://perldoc.perl.org/index-modules-F.html

Current website has a single list of ALL the core modules. This is slightly unwieldy and a little hard to read.

**Comment by Grinnz** [comment]
While I agree that the current modules index page needs improvement, I am very against the idea of separate pages by letter.

**Comment by Grinnz** [comment]
I've reformatted it into a tighter list similar to the alphabetical list on the functions index; is that any better?

**Comment by scottchiefbaker** [comment]
Yes this is much more usuable. Thank you for the quick response.

Question though, why is `IO::Socket::IP`, and `Socket` out of order, and in a different font?

**Comment by Grinnz** [comment]
This is because their documentation wraps the module name in `C<>` tags which confuses the perlmodlib generator (the source for this page). I could strip the `C<>` but really this needs to be fixed in either those modules or the perlmodlib generator.

**Comment by Grinnz** [comment]
Closing because I don't intend to replicate the (in my opinion) mistake of separating indexes by letter, but any other suggestions for improvement would be appreciated.
