### ISSUE TITLE
Math::BigRat->bdiv()

### ISSUE THREAD

**Issue by ShaunGriffithRyff** [Grinnz/perldoc-browser#49]
In the bdiv() section, the last term appears to be `$x- bmod($y)>` (though the code highlighting stops after `$x-`). From my local copy in perldoc, this part seems correct (`$x->bmod($y)`), so I wonder if the perldoc browser parser has failed here?

The source of the webpage has `<code>$x-</code>bmod($y)&gt;`, when I would expect `<code>$x->bmod($y)</code>;` (I think).

[Separately, the original module source misspells "remainder" as "remainer" once in that section, but I've reported that to the maintainer.]

Cheers!

**Comment by Grinnz** [comment]
This is a POD error by the maintainer. `C<$x->bmod($y)>` should be `C<< $x->bmod($y) >>` or `C<$x-E<gt>bmod($y)>`. See https://perldoc.perl.org/perlpodspec#Pod-Formatting-Codes

**Comment by Grinnz** [comment]
The Math::BigRat issue tracker is at https://rt.cpan.org/Public/Dist/Display.html?Name=Math-BigRat.
