### ISSUE TITLE
insufficient text contrast in `nav`

### ISSUE THREAD

**Issue by daxim** [Grinnz/perldoc-browser#5]
https://webaim.org/resources/contrastchecker/?fcolor=9A9DA0&bcolor=343A40

**Comment by Grinnz** [comment]
Do you have any suggestions? Otherwise I can mess with it.

**Comment by Grinnz** [comment]
One component to keep in mind with this is that there needs to be a visible contrast between the standard color and the hover color as well.

**Comment by daxim** [comment]
Fulfills the minimum contrast requirements:

    .nav-link { color: #ccc }
    .nav-link:hover { color: #fff }

Even better a11y would be something like

    .nav-link { color: #fff }
    .nav-link:hover {
        text-decoration: underline;
        /* or */
        border: 0.1em outset #fff;
    }

because that makes colour not the sole distinguishing feature.

**Comment by Grinnz** [comment]
Thank you. I don't feel that the hover-underline or border styles fit with the site, and the border messes with the layout, so I went with the first method.
