### ISSUE TITLE
wrong syntax highlight of perl code

### ISSUE THREAD

**Issue by Freed-Wu** [Grinnz/perldoc-browser#53]
See <https://github.com/Perl/perl5/issues/20640>

**Comment by Grinnz** [comment]
Syntax highlighting is managed by highlight.js. Not much I could do currently except update the packed asset and hope it gets fixed.

**Comment by Grinnz** [comment]
Updated to latest highlight.js in https://github.com/Grinnz/perldoc-browser/commit/0eb98503980eb37f6304b6797ca0ed6e0860b357 and it seems to have fixed the issue although it still isn't able to handle the C code embedded at the end but that's expected. May need to clear cache to retrieve the updated JS asset. Thanks for the report
