### ISSUE TITLE
Table of contents links no longer work

### ISSUE THREAD

**Issue by happy5214** [Grinnz/perldoc-browser#54]
The `a` HTML elements in the `code` blocks are being removed by at least Firefox 108.0, apparently for security reasons (the browser console complains about them being unescaped). This causes all of the links in the main table of contents to be stripped and turned into plain code text, rendering the ToC mostly useless.

**Comment by WRSomsky** [comment]
The same happens w/ a chrome browser on my mobile phone: no links.  Chrome 109.0 Android 13 Pixel 7

**Comment by peterdd** [comment]
I can confirm this with Firefox 109,

Links are rendered when `javascript.enabled` is off in the `about:config`

So can be seen as highlight.js-issue? (https://github.com/highlightjs/highlight.js/wiki/security)
![perldoc-highlightjs](https://user-images.githubusercontent.com/1839154/214782510-3d947f09-e59a-4ad5-ad6f-ff67a78ee624.png)

**Comment by haarg** [comment]
This is caused by a combination of updating highlight.js and 4c47d7cda22fa8af9a580fb491e66cf4c1f356fb. I'm not really clear what the purpose of using `plaintext` rather than `nohighlight` is.

**Comment by Grinnz** [comment]
That's annoying. Regardless it's only an issue for these customized code blocks on that page. Would be more of an issue if we wanted to insert links into code snippets like the old perldoc site did.

**Comment by Grinnz** [comment]
Thanks for the example, I didn't know what was meant by "table of contents" since that refers to the list at the top of the page.

**Comment by Grinnz** [comment]
I need to re-render each perl with this change but it should be fixed by tomorrow. Thanks for the report!
