### ISSUE TITLE
blead is called a release 

### ISSUE THREAD

**Issue by rwp0** [Grinnz/perldoc-browser#56]
First off, thank you for allowing us to read blead Perl documentation.

> You are viewing the version of this documentation from Perl blead. This is a development **release** of Perl.

Is it really a "release" or more appropriately a version?

Maybe a special wording needed here (rather than using the common dev template text) mentioning that it's (ie. blead) the latest development version/stage/form available.

Thanks

**Comment by Grinnz** [comment]
The wording was written for the actual development releases, but this is a fair point when the version is blead.
