### ISSUE TITLE
Please increase text contrast! (aid stopping the madness of low contrast)

### ISSUE THREAD

**Issue by hadjiprocopis** [Grinnz/perldoc-browser#58]
Personally, I find the contrast between normal text (see e.g. https://perldoc.perl.org/perlform, color #445555) and the background (color #fff) too low for a doc-browser in which the user must be assisted in concentrating on the content and not squint to read it.

Lack of contrast is so disturbing **for me** that often I resort to reading the doc from man-pages via my terminal. Albeit not as practical, at least I don't squint and wrinkle this way.

I believe that increasing the contrast of Perl doc browser will not decrease a user's ability to read Perl documentation neither will degrade the user experience. On the contrary, the former will be vastly improved and the latter well ... hmmm ... please, just make a quick opinion poll and see for yourselfs. I have done one at Perlmonks.org and got 100% agreement (4/4, including me).

Personally, a black (#000000) text on the already white background will allow me to open the curtains and get some sunlight. And from what little HTML I know, it is a matter of changing text color #445555 to #000000. And once at it, why not change contents color which is currently #2a2a2a and code blocks color which is currently #2f3337. All to black.

**Please bring some light to our programmer's life with adding more black color!**

OT: I do not understand which marketing guru the "low contrast" madness came from but, AFAIC, it has spread like the plague, it makes my browser-reading a misery (github where this issue is edited has also this low-contrast policy) and proves that after some time, design improvements kill the product.

Many thanks for the Perl doc browser which is very helpful otherwise,

5min edit: P.s. I understand that the HTML theme/CSS  of the Perldoc browser may have been taken from somewhere and therefore it may not be a design choice of the creators of the Perldoc browser.

bw bliako

**Comment by Tux** [comment]
I agree. Related: please stop making dark-theme default without having a decent light-theme available in way too many applications. To people like me it makes me not even *want* to delve into features, as all the fun has gone before even starting. De gustibus non est disputandum.

**Comment by Grinnz** [comment]
> I agree. Related: please stop making dark-theme default without having a decent light-theme available in way too many applications. To people like me it makes me not even _want_ to delve into features, as all the fun has gone before even starting. De gustibus non est disputandum.

I'm not sure the relevance as #33 has not even been implemented yet 😄

**Comment by Grinnz** [comment]
I've applied a darker font color in https://github.com/Grinnz/perldoc-browser/commit/76dd3b14dcffb243baeeec4221b57dbd0476a712. The code block coloring is applied by highlight.js and not our stylesheet. Thanks for the feedback!

**Comment by hadjiprocopis** [comment]
THANK YOU
