### ISSUE TITLE
bad link on "warnings" page

### ISSUE THREAD

**Issue by myrrhlin** [Grinnz/perldoc-browser#65]
On the page:

https://perldoc.perl.org/5.6.0/warnings

is the link: 

> See ["Pragmatic Modules" in perlmod](https://perldoc.perl.org/5.6.0/perlmod#Pragmatic-Modules) and

But it should be:

> See ["Pragmatic Modules" in perlmodlib](https://perldoc.perl.org/5.6.0/perlmodlib#Pragmatic-Modules) and

I checked: same links on 5.6.1 and 5.6.2 are correct.

**Comment by Grinnz** [comment]
That is how it is linked in that version of the source documentation. Clearly it was fixed in 5.6.1. There's nothing I can do here.
