### ISSUE TITLE
Not accessible from Russia

### ISSUE THREAD

**Issue by OpossumPetya** [Grinnz/perldoc-browser#7]
The https://perldoc.pl/ is not accessible in Russia because IP of your host is blocked. Probably due to Russia gov't 's quest to block Telegram messenger. This is not something you need to take action On ('cause you never know what they'll block next), but merely for your information...

https://blocklist.rkn.gov.ru/ - to check IPs

**Comment by Grinnz** [comment]
That's unfortunate :frowning_face: You can use https://perldoc.grinnz.com (my sandbox site) if you really want to access it but it's not meant to be reliable.

**Comment by Grinnz** [comment]
I have changed the IP of the server. Hopefully this works around the issue for now.

**Comment by OpossumPetya** [comment]
works now, thank you!
